language: go

sudo: false

env:
  global:
    - GO111MODULE=on

go:
  - "1.12"

cache:
  directories:
    - $GOPATH/pkg/mod

install:
  - make setup_ci

script:
  - make build
  - make test
  - make lint 
